//
//  ViewController.swift
//  screen filler
//
//  Created by Russell Mirabelli on 9/26/19.
//  Copyright © 2019 Russell Mirabelli. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    let lorem = """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec ullamcorper sit amet risus nullam eget. Amet cursus sit amet dictum sit amet justo donec enim. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Sit amet facilisis magna etiam tempor orci eu lobortis. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Aliquet porttitor lacus luctus accumsan. Tellus molestie nunc non blandit massa enim nec dui. Ante in nibh mauris cursus mattis molestie a.

    Imperdiet sed euismod nisi porta. Diam vel quam elementum pulvinar. Nibh nisl condimentum id venenatis a condimentum vitae. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Quis auctor elit sed vulputate mi sit amet mauris commodo. Dis parturient montes nascetur ridiculus mus mauris. In dictum non consectetur a. Ante in nibh mauris cursus mattis molestie. Varius duis at consectetur lorem donec massa sapien. Nullam eget felis eget nunc lobortis mattis aliquam. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Leo vel fringilla est ullamcorper eget nulla facilisi. Blandit massa enim nec dui nunc. Non diam phasellus vestibulum lorem sed risus. Dolor sit amet consectetur adipiscing. Odio ut sem nulla pharetra diam.

    Urna duis convallis convallis tellus id interdum. Nulla aliquet porttitor lacus luctus accumsan. Id velit ut tortor pretium. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Dignissim suspendisse in est ante. Ornare arcu odio ut sem nulla pharetra. Rutrum quisque non tellus orci ac. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Ornare arcu dui vivamus arcu. Eu nisl nunc mi ipsum faucibus. Mauris cursus mattis molestie a iaculis. Tortor at risus viverra adipiscing at in tellus. Nec dui nunc mattis enim ut tellus elementum sagittis. Non sodales neque sodales ut etiam sit. Faucibus in ornare quam viverra orci sagittis eu volutpat. Libero id faucibus nisl tincidunt eget nullam non. Id diam maecenas ultricies mi eget. Sem nulla pharetra diam sit amet. Duis at tellus at urna condimentum mattis pellentesque id nibh. At augue eget arcu dictum.

    Elementum tempus egestas sed sed risus. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Sodales neque sodales ut etiam sit amet nisl. Elementum facilisis leo vel fringilla est ullamcorper. Neque convallis a cras semper auctor neque vitae tempus. Nullam eget felis eget nunc. At consectetur lorem donec massa sapien faucibus et molestie ac. Arcu odio ut sem nulla pharetra. Pellentesque id nibh tortor id aliquet. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Commodo sed egestas egestas fringilla phasellus faucibus. Mauris rhoncus aenean vel elit.

    In dictum non consectetur a erat nam at lectus. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Proin nibh nisl condimentum id venenatis a. Non diam phasellus vestibulum lorem. Urna id volutpat lacus laoreet non curabitur. Suspendisse potenti nullam ac tortor vitae purus faucibus. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Tristique et egestas quis ipsum suspendisse. Porta nibh venenatis cras sed felis eget. At urna condimentum mattis pellentesque id nibh tortor id. Massa id neque aliquam vestibulum morbi blandit. Varius quam quisque id diam vel quam. Sem nulla pharetra diam sit amet nisl. Adipiscing enim eu turpis egestas pretium.

    Ultrices dui sapien eget mi proin sed libero. Sed vulputate odio ut enim blandit. Dignissim sodales ut eu sem integer vitae. Vehicula ipsum a arcu cursus vitae. Netus et malesuada fames ac. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. In est ante in nibh mauris cursus mattis molestie. Vel facilisis volutpat est velit egestas dui id ornare arcu. Facilisis sed odio morbi quis commodo odio aenean. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Nec ultrices dui sapien eget mi proin. Egestas diam in arcu cursus euismod quis viverra. Purus in mollis nunc sed id semper risus in. Non diam phasellus vestibulum lorem.

    Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Ut ornare lectus sit amet. Risus pretium quam vulputate dignissim suspendisse in est ante in. Est ullamcorper eget nulla facilisi etiam dignissim diam. Sem et tortor consequat id porta nibh venenatis cras sed. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Semper viverra nam libero justo laoreet sit amet cursus sit. Bibendum neque egestas congue quisque egestas diam. Bibendum neque egestas congue quisque egestas diam in arcu. Eget lorem dolor sed viverra ipsum nunc. Diam vulputate ut pharetra sit amet. Faucibus ornare suspendisse sed nisi lacus. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Sed libero enim sed faucibus.

    Id semper risus in hendrerit gravida rutrum. In dictum non consectetur a erat nam at lectus. Lectus sit amet est placerat in egestas erat imperdiet sed. Ac turpis egestas maecenas pharetra convallis posuere morbi leo. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Sit amet dictum sit amet justo donec enim. Diam volutpat commodo sed egestas egestas fringilla phasellus. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Integer quis auctor elit sed vulputate mi sit amet mauris. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Est velit egestas dui id ornare. Aliquam sem et tortor consequat id porta. In eu mi bibendum neque egestas congue quisque egestas diam. Nunc mi ipsum faucibus vitae aliquet. Pulvinar neque laoreet suspendisse interdum consectetur.

    Dui vivamus arcu felis bibendum ut tristique et egestas. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Tincidunt eget nullam non nisi est sit amet. Elit sed vulputate mi sit amet mauris. Vel orci porta non pulvinar neque. Amet aliquam id diam maecenas ultricies mi. Nullam non nisi est sit amet facilisis magna. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Ac tincidunt vitae semper quis lectus nulla. Cras ornare arcu dui vivamus arcu. Nisl rhoncus mattis rhoncus urna neque viverra. Eget aliquet nibh praesent tristique. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Eu lobortis elementum nibh tellus molestie nunc non blandit. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. In iaculis nunc sed augue lacus viverra.

    Gravida quis blandit turpis cursus in hac habitasse platea. Dolor sit amet consectetur adipiscing elit. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Volutpat odio facilisis mauris sit amet massa vitae. Sed nisi lacus sed viverra tellus. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Porttitor leo a diam sollicitudin tempor id eu. Facilisi etiam dignissim diam quis enim lobortis. Sollicitudin ac orci phasellus egestas tellus rutrum. Elementum curabitur vitae nunc sed velit dignissim sodales ut.

    Lorem mollis aliquam ut porttitor leo. Eget dolor morbi non arcu. Sed libero enim sed faucibus turpis. In massa tempor nec feugiat nisl pretium fusce id velit. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Enim nunc faucibus a pellentesque sit amet porttitor eget. In nisl nisi scelerisque eu ultrices vitae auctor eu. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Tortor condimentum lacinia quis vel eros donec ac odio. Tristique senectus et netus et malesuada fames. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci. Varius quam quisque id diam vel. Imperdiet massa tincidunt nunc pulvinar sapien et. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Proin sagittis nisl rhoncus mattis rhoncus. Ut tristique et egestas quis ipsum suspendisse. Cursus risus at ultrices mi tempus imperdiet nulla. Quis hendrerit dolor magna eget est. Donec ac odio tempor orci.

    Eget nulla facilisi etiam dignissim diam quis enim. Tempor nec feugiat nisl pretium. In tellus integer feugiat scelerisque varius morbi. Fermentum posuere urna nec tincidunt praesent semper. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Duis at tellus at urna condimentum. Quisque non tellus orci ac auctor augue mauris augue. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Sagittis vitae et leo duis. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Ac turpis egestas sed tempus urna et. Egestas sed tempus urna et pharetra pharetra. Tortor condimentum lacinia quis vel eros donec ac odio.

    Tortor at risus viverra adipiscing at in tellus integer. Placerat vestibulum lectus mauris ultrices eros. In aliquam sem fringilla ut morbi tincidunt augue. Blandit libero volutpat sed cras ornare. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Ut aliquam purus sit amet luctus venenatis lectus magna. Pulvinar elementum integer enim neque. Vitae ultricies leo integer malesuada nunc. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Vitae nunc sed velit dignissim sodales ut eu sem integer. Pellentesque massa placerat duis ultricies lacus sed turpis. Porta lorem mollis aliquam ut porttitor leo. Sed viverra ipsum nunc aliquet bibendum enim. Ultricies integer quis auctor elit. Purus sit amet volutpat consequat mauris.

    Tincidunt dui ut ornare lectus sit amet est. Vivamus at augue eget arcu dictum. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Enim neque volutpat ac tincidunt vitae semper quis. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Cursus risus at ultrices mi tempus imperdiet. Morbi tempus iaculis urna id volutpat lacus. Duis ut diam quam nulla porttitor massa id neque aliquam.

    Vitae suscipit tellus mauris a diam maecenas sed enim. Arcu odio ut sem nulla pharetra diam sit amet. Nunc sed blandit libero volutpat sed. Nulla aliquet enim tortor at auctor urna nunc id. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Nunc aliquet bibendum enim facilisis gravida neque convallis. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Nec nam aliquam sem et. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Hac habitasse platea dictumst quisque sagittis. Velit egestas dui id ornare arcu odio ut sem. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Imperdiet proin fermentum leo vel. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt.
    """
    @IBOutlet weak var label: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        label.text = lorem
        
        let fullscreenFrame = view.frame
        let newRect = CGRect(x: 10, y: 10, width: Int(fullscreenFrame.width - 20.0), height: Int(fullscreenFrame.height - 20.0))
        let insetRect = fullscreenFrame.insetBy(dx: 10.0, dy: 10.0)
        label.frame = insetRect
    }

}

